<?php

/**
 * @file
 * Contains mycustom.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mycustom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mycustom module.
    case 'help.page.mycustom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My custom module for training') . '</p>';
      return $output;

    default:
  }
}
